### ISSUE TITLE
Deploy Not Triggering

### ISSUE THREAD

**Issue by Darthmaul** [crgeary/wp-jamstack-deployments#1]
Hey there! Really awesome plugin. I tested it on a website hosted on pantheon.io, and it worked perfectly.

Now I'm using a shared hosting setup, and I can't get the webhook to fire off. Even when I click the deploy button a deploy doesn't trigger.

Any idea what could be causing this?

Also, when I save my settings the webhook URL keeps disappearing.

Thanks!

Edit: it seems that after creating a new webhook and adding it, the setting saved and it works now. Any idea what would cause this behavior?

**Comment by crgeary** [comment]
Hmm, I haven't come across either of these before...

For the issue with the webhook not triggering:

1. Do you get redirected to `admin.php?page=wp-jamstack-deployments-settings` after you have clicked on the site deployment the button?

2. Are you able to test that `wp_safe_remote_post()` or `wp_safe_remote_get()` work ok for you on your shared hosting server. Here's some example code you could add to test it:

```
add_action('init', function () {
    if (!isset($_GET['crgeary']) || 'jamstack-deployment-trigger' !== $_GET['crgeary']) {
        return;
    }

    // update this to your webhook
    $webhook = 'https://...';

    wp_safe_remote_post($webhook, [
        'blocking' => false
    );
});
```

Add this test code to either your themes `functions.php` or as a custom plugin. Whichever you would prefer... Then visit your sites homepage with `?crgeary=jamstack-deployment-trigger-test` appended to the end of the URL. This should then trigger the webhook.

3. Can you check for any PHP errors, either by turning WP_DEBUG on inside `wp-config.php`, or by checking the PHP error logs.

* * *

I also haven't come across the issue with settings not saving before either, and I've used this same code for settings on various projects, so I would feel fairly confident the issue isn't there (hopefully anyway).

It sounds like this might be related to caching, if you had the site on pantheon, perhaps they added code to the site that added caching. (sorry, i haven't used Pantheon before).

* * *

Please, feel free to get back in touch if none of this help you debug :)

**Comment by Darthmaul** [comment]
No worries, thanks for the response! 

I can throw that code in and check back with any errors if they come up in the future. Right now, honestly it's working fine. The deploys are triggering and everything looks copasetic. It was just really weird that the setting wasn't saving for a while(on the shared hosting setup not pantheon).

Caching might be the issue, but again I don't know. It was such a weird behavior it might have just been something on my end for a little while.

Either way, I'm confident that this is resolved so I will close. If I ever have any more issues/errors and the code you posted doesn't work, I'll check back in!

Thanks again for making this plugin! It's really sweet!
