### ISSUE TITLE
Add filter to API args

### ISSUE THREAD

**Issue by mAAdhaTTah** [crgeary/wp-jamstack-deployments#11]
I'd like to use this to trigger deployments against an API that needs a token. I could add it to the request via environment variable but there isn't any way to hook into that. Could you add a filter to the request arguments?

**Comment by crgeary** [comment]
@mAAdhaTTah thanks for the suggestion, all done for you 👍

**Comment by mAAdhaTTah** [comment]
Thank you for the quick response!
