### ISSUE TITLE
Webhook URL Won't Save in Settings With Any Spaces

### ISSUE THREAD

**Issue by brianjohnhanna** [crgeary/wp-jamstack-deployments#13]
Plugin settings initially seemed broken to me because when I copied and pasted the build webhook URL from Netlify it came with a couple spaces at the beginning of the string. 

I haven't had a chance to check how the validation is working, but I guess it was not saving as a valid URL (but also wasn't producing any errors) because of the spaces. I suggest, since most people will be copying/pasting that before validating any input you apply the [`trim()`](https://www.php.net/manual/en/function.trim.php) PHP function to strip out any whitespace at the beginning or end of the string.

I can try and do a PR when I have a little more time.

**Comment by crgeary** [comment]
Thanks for raising this @brianjohnhanna, this'll be include in the next release.
