### ISSUE TITLE
Unable to activate the extension on WP 5.2.3

### ISSUE THREAD

**Issue by kvalium** [crgeary/wp-jamstack-deployments#17]
Hello, 

I've installed this extension throught th the WP extensions admin page, i've a warning about the fact that the extension was not tested with my version of WP but i can install it. 

The problem is that i can't activate the extension, each time i click on "Activate" on the extensions list, extension still disabled...

**Comment by crgeary** [comment]
Hey,

I too am running 5.2.3, and this does install & activate without an issue.

Could you disable all other plugins, and switch to the twentynineteen theme and try to activate the plugin. My first guess would be that another plugin or theme is preventing this from activating.

If this still does not work. Could you please paste the contents of the site health check (Tools > Site Health > Info) so I can attempt to replicate.

Thanks

**Comment by kvalium** [comment]
Ok so i've re-installed the extension, activation works at first try...
Probably my WP was in a bad mood tuesday...
