### ISSUE TITLE
Test button doesn't seem to do anything

### ISSUE THREAD

**Issue by laurenskling** [crgeary/wp-jamstack-deployments#18]
What is supposed to happen when I press the test button?

There doesn't seem to be a deploy triggered or any message given.

**Comment by crgeary** [comment]
It triggers a deploy based on the settings you have provided. Have you added any settings? Can you provide some more information about your setup, and your settings?

**Comment by laurenskling** [comment]
Yes i've made the correct settings and added a hook to my posts and pages. It works when I save a post, but the test button doesn't do anything. It doesn't give a (alert) message, is it supposed to?

**Comment by crgeary** [comment]
Ah, I see the issue... The `Test Webhook` button indeed does not work. However, the standard deployment button in the admin bar, and triggering when saving content should work.

I'll look at a fix as soon as I get some free time.

**Comment by laurenskling** [comment]
Thanks.

So the test button will actually kick off a deployment? Is that a test I wonder? 🤔

**Comment by crgeary** [comment]
Yep it'll kick off a deployment. I would say that's a test. I'll rename it to say "Test Deploy" as that'll be a little more informative as to what it'll do.

Sorry I haven't had the chance to sort this out. I'll aim to do it this week. :)

**Comment by laurenskling** [comment]
Thanks :)

**Comment by crgeary** [comment]
Sorry it took so long to do, have had a busy few weeks. Should be deployed to WordPress repository now with fixes for this, and your other issue :)

Thanks for the suggestions 👍
