### ISSUE TITLE
Deploy button in Admin Bar doesn't have a href?

### ISSUE THREAD

**Issue by laurenskling** [crgeary/wp-jamstack-deployments#19]
It's void in this code as well https://github.com/crgeary/wp-jamstack-deployments/blob/bd7913cf417112b3841a9ba982c2bcdef03bbb90/src/WebhookTrigger.php#L197 🤔  

What is the plan?

**Comment by crgeary** [comment]
Submission is via AJAX, doesn't need a `href`.. I suppose I could change it so that it falls back to a normal request, but it should work for you either way.

You have't stated what your issue is here, the plugin works.
