### ISSUE TITLE
Add notification to show a deployment was triggered

### ISSUE THREAD

**Issue by crgeary** [crgeary/wp-jamstack-deployments#2]
When you manually trigger a deployment, there's no visual feedback to let you know that a deployment was triggered. We should really have a little status bar, like the ones you get when you save a post, just to say `"A deployment was triggered."` or similar.

**Comment by CHEWX** [comment]
Hi,

Is there a callback from Netlify too? My client will not know once it's live except by checking, it would be good if it said deployed. Or Last Deployed. Not initiated but complete.

Thanks,
Tom

**Comment by crgeary** [comment]
So, I can't get this information from the webhook, as it's run asynchronously.. However, it would be possible to either:

1. Get the data via the Netlify API. Perhaps poll their API every 30 seconds or so to check for a completed deployment.
2. Setup a post processing webhook to notify WordPress that the site has deployed.

Both of these methods would require extra development as they're not part of the current plugin. I'm currently short on time, but could look at doing this in the future.

Thanks for the suggestion :)

--

If you would like a quick solution, you can send an email on successful deployment. Have a look here:

```
https://app.netlify.com/sites/{YOURPROJECTSLUG}/settings/deploys#deploy-notifications
```

**Comment by cschweda** [comment]
Another way to check deployment status is to check the Netlify status badge:

https://www.netlify.com/blog/2019/01/29/sharing-the-love-with-netlify-deployment-badges/

This might not be the best way -- but the badge SVG ('successful',  'building', 'failed') is updated in realtime. I poll the badge when the build is triggered -- and then I allow the client to hit a ```refresh``` button that triggers a refresh method that includes polling the badge again.

I'm using Vue and Vuetify. My code to display the badge is simply:

```
            <img 
              :src="getBadge()" 
              alt="Netlify Status">
         
```

And then the ```getBadge()``` method simply returns the current badge (with a ```Date``` object to make sure nothing is cached):

```
getBadge() {
      return (
        'https://api.netlify.com/api/v1/badges/d5c16bbf-7380-49d8-8cad-363de97f4dab/deploy-status?' +
        new Date()
      )
    }
```
Probably not the best way to update status -- but (for me, at least) it was the easiest and quickest. And it works great to give a visual indication of the build status. (I could remove the manual refresh and trigger the badge check every, say, 15 seconds or so -- but the manual refresh works fine.)

**Comment by CHEWX** [comment]
Thanks @cschweda — I'll take a look at those approaches.

Aside, why does the "DEPLOY" button take you to the settings page? When the client pressed the button they were taken to a settings page, they didn't know whether it deployed so kept clicking. 

Kind of related to this thread but I think it should just return false, change texting to 'deploying...', then a simple timeout back to 'deploy'?

**Comment by crgeary** [comment]
@CHEWX Yeah that was kind of a dumb decision when I implemented it. It was a quick solution, that I never got around to changing. I'll have a look at improving it this week.

Thanks for the idea @cschweda, I'll get this in the admin area somewhere at the same time.

I could probably do it this weekend.

**Comment by crgeary** [comment]
@CHEWX @cschweda 

This is now done. I've updated the plugin repo.

**Comment by CHEWX** [comment]
Nice @crgeary — works really well.
