### ISSUE TITLE
QUESTION: Use Custom Endopoint instead of Netlify

### ISSUE THREAD

**Issue by jimmysafe** [crgeary/wp-jamstack-deployments#21]
Hi, I really love your plugin and it helped me a lot with what i wanted to do. Thank you very much!

At the moment i have wordpress hosted on digital ocean and gatsby hosted on netlify.

I wanted to move the gatsby from netlify to digital ocean, so the CMS and the front end are in the same place.

I haven't tested this yet and i was wondering:
Can I create a custom endpoint that on hit runs the gatsby build everytime i click your plugin button? 
Obviously instead of the Netlify build hook i will input the custom endpoint address in your plugin field.

Hope you might help with my query,

thanks in advance,

keep up the great work!

**Comment by crgeary** [comment]
You're welcome, I'm glad you've found it helpful.

Absolutely yes, you can. It should support any service or custom solution as long as you provide a valid URL in the settings. (This is also true for the badge, this is not Netlify specific either).

I should maybe make this clearer. Thanks for asking about it. 👍
