### ISSUE TITLE
Feedback from a first time user

### ISSUE THREAD

**Issue by Benunc** [crgeary/wp-jamstack-deployments#25]
I love the plugin,got it up and running in no time. I have a few pieces of feedback regarding the inline documentation, in case others are running into issues:

1. Calling it a "Webhook URL" on the settings page is not helpful, and the link currently goes to Netlify's webhooks docs. Webhook URLs indicate that Netlify would be pinging the site after a deploy, which is the opposite of what we are going for. Instead if you call it a "Build Hook URL" and link instead to https://docs.netlify.com/configure-builds/build-hooks/ that gets folks on the right track. Luckily the screenshots in your plugin readme show that it's a build hook URL, so I figured it out fairly quickly. This may be a function of it being for not just netlify, but I was confused for sure. The help text could be updated there. 

2. I wasn't totally clear during setup what the Status badges are used for, but figured out (again thanks to the screenshot) what's going on. Here's how I'd recommend changing that wording: There are two URLs needed here, one for the image of the badge which should look like https://api.netlify.com/api/v1/badges/random-string/deploy-status and one that linkes directly to the site. 

I am happy to submit a PR for those changes to the inline docs there on the page, if you'd like. 

Thanks for a great plugin!

**Comment by crgeary** [comment]
Thank you so much @Benunc!

These are great improvements, and thanks for rolling them into a PR for me. Well spotted on the webhook url, that was a bit of an oversight. 😉 

This has all been deployed, so you should see an update shortly 👍
