### ISSUE TITLE
What to do with future publications

### ISSUE THREAD

**Issue by laurenskling** [crgeary/wp-jamstack-deployments#27]
So when you write a post and set the publication in the future, only on save a trigger will be sent, right?

How would one go about to also trigger a deploy when the publication date hits

Thanks so much

**Comment by crgeary** [comment]
Hmm. That's a good catch.

You can use the `transition_post_status` action for this. This is something I would say the `wp-jamstack-deployments` plugin should do, so i'll add this in ASAP for you.

Thanks for the suggestion. I'll aim to do this for you in the next few days.

**Comment by laurenskling** [comment]
That would be fantastic :)

**Comment by crgeary** [comment]
All done. Live on the plugin repository for you.

Thanks! 👍

**Comment by laurenskling** [comment]
So, I think the PR isn't really solving for what I was aiming for.

In wordpress, you can set a publication date in the future;
If we are creating a JAMstack website, we need the trigger to run, _at that datetime_ to build the new version of the website with that post included. We need a cron or something to trigger a deploy

**Comment by crgeary** [comment]
Can you please test it, because this does exactly what you asked for.

Feel free to raise another issue if it doesn't work.

**Comment by laurenskling** [comment]
Sorry for the long wait, I didn't have a good use case at hand I could test. I can now confirm this is perfectly working for me :) Thanks so much
