### ISSUE TITLE
`[]` characters get escaped and removed in the URL

### ISSUE THREAD

**Issue by laurenskling** [crgeary/wp-jamstack-deployments#30]
I'm using your plugin to call my Gitlab pipeline; 

In the docs, they state you can add variables as so:
`https://gitlab.com/api/v4/projects/PROJECT/ref/REF_NAME/trigger/pipeline?token=TOKEN&variables[RUN_NIGHTLY_BUILD]=true`

When I write the url like this in the Build Hook URL, the first time `[` and `]` they will get rewritten to `%5B` and `%5D`, the time you save that they will be removed from the string. So my URL string is broken. 

Any idea how we can allow for this characters in this (or these) field(s)?

**Comment by crgeary** [comment]
If the URL was to be replaced with`%5B` and `%5D`, as it does now, but NOT removed when you save it the second time around, would this work?

**Comment by crgeary** [comment]
Fixed in 0.4.1

**Comment by laurenskling** [comment]
Can confirm it works! Thanks!
