### ISSUE TITLE
"Trying to access array offset on value of type bool" notice being thrown

### ISSUE THREAD

**Issue by kellenmace** [crgeary/wp-jamstack-deployments#34]
In the `triggerSavePost()` method, the options are retrieved like this `$option = jamstack_deployments_get_options();`, then this logic is run on the next line:
`$option['webhook_post_types'] ?: []`.

If the user has not saved post types previously on the options page though, `$option` will be set to `false`, and trying to access `$option['webhook_post_types']` will result in a "Trying to access array offset on value of type bool" notice being thrown.

Submitting a PR to fix that.

**Comment by crgeary** [comment]
Just deployed this as part of v1.0.0
