### ISSUE TITLE
Optionally disable requests for **private** posts or pages?

### ISSUE THREAD

**Issue by hrdlnk** [crgeary/wp-jamstack-deployments#37]
Love the plugin!

How about an option to disable requests for updates made to **private** posts or pages?

**Comment by crgeary** [comment]
Hmm, yeah that would be a nice addition. Thanks!

I'll have a look and see what I can do. I'd prefer to just support "post statuses" in general, similar to how you can choose post types from the settings. But that sounds like it would also work for you.

I hope to have a look at something else on the plugin next week, so I'll try to fit this in too for you.

**Comment by crgeary** [comment]
@hrdlnk I wasn't able to get to this last week, but it's now live on the WordPress plugin repo for you v1.0.0
