### ISSUE TITLE
Feature: Trigger deploy from editing ACF options page

### ISSUE THREAD

**Issue by breadadams** [crgeary/wp-jamstack-deployments#38]
We're using this plugin on a few sites that have some configuration via an ACF options page, and would like to be able to trigger a deploy when editing said options pages.

Does this sound like something that fits the scope of the project?

**Comment by crgeary** [comment]
I probably can't get to it until next week, but yeah i'd be happy to add that in to the plugin. Thanks for the suggestion!

I'll let you know when it's added & released.

**Comment by crgeary** [comment]
@breadadams I wasn't able to get to this last week, but it's now live on the WordPress plugin repo for you v1.0.0

**Comment by breadadams** [comment]
Yep, just got a notification @crgeary. Installed v1.1.0 and verified that it's working, thanks a lot! 😃
