### ISSUE TITLE
How to use this plugin for an existing remote wordpress site?

### ISSUE THREAD

**Issue by lt-shy-john** [crgeary/wp-jamstack-deployments#45]
Hello, I am a beginner of using Netlify and I was hoping this plugin would deploy my existing WordPress site into Netlify. 

What I did was I created a blank Github repository and expecting that this plugin will migrate my site into there. Am I right? 

After that I clicked on the "Test Deployment" button I don't see anything weird, but the Github repository I mentioned has no changes. Have I done anything wrong?

**Comment by crgeary** [comment]
Hey,

Unfortunately, it doesn't work quite as you expect it to. Have a read through issue #31 which is very similar to your situation, and might help to provide clarity.

Perhaps you would be more interested in a solution like this: https://wp2static.com/

Feel free to follow up if you have any questions, whether it be about this plugin or where you could start with Netlify 👍

**Comment by lt-shy-john** [comment]
Thanks, I'll have a look at the links. They seemed useful to me.
