### ISSUE TITLE
Deploy button reloads page instead of POSTing to build hook

### ISSUE THREAD

**Issue by bengal75** [crgeary/wp-jamstack-deployments#47]
Started to run into an issue yesterday where pressing the Deploy Website button would reload the page instead of making a POST request to the configured build hook URL.

After some investigation, it seemed that the affected sites had been auto-upgraded to WordPress 5.5.x (mainly from 5.3.x), and according to [this article](https://wptavern.com/major-jquery-changes-on-the-way-for-wordpress-5-5-and-beyond), there have been some major changes in how WP includes jQuery Migrate starting with this version.

The WP team has released a [workaround plugin](https://wordpress.org/plugins/enable-jquery-migrate-helper/), and installing this on our sites seems to allow the Deploy button to work as expected again. However, they've stated that this is only supposed to be a solution until WP 5.6, when things will change again, and plugins should ideally make updates so they don't depend on jQuery Migrate.

This is where I reach the limit of my knowledge - how possible is it to make such an update for this plugin?

**Comment by crgeary** [comment]
Thanks for raising it! That does indeed sound like a potential cause, so it's possible I am using some out dated jQuery code somewhere (although there isn't much). I'll take a look, and see if I can replicate it.

**Comment by crgeary** [comment]
@bengal75 I've tested this on 5.5.3 and I cannot see any issues. It works as it should on my end.

Could you disable all other plugins, and switch to one of the default themes and check to see if the issue still persists. If it does still exist after that, could you send a screenshot of your browser console?

Thanks :)

**Comment by bengal75** [comment]
@crgeary Thanks so much for looking into it! We tried some of your suggestions and it quickly became apparent that it was actually another plugin which was using some outdated jQuery, and therefore crashing the JS thread for all plugins on the page - evidently before this plugin's code could run successfully.

Updating the other plugin has restored the button's functionality, and we are no longer relying on the workaround plugin. The moral of the story seems to be "update all your plugins". Thanks again for your help; it's especially appreciated since it's not this plugin that actually caused the issue!
