### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by metiqls** [crgeary/wp-jamstack-deployments#48]
Is anyone able to help set this up or provide a video walkthrough?

Additionally, I'm looking to create a website as a service (WaaS) using Wordpress as the CMS, and be able to deploy the individual sites statically then shut down WP when not in use.  

Thanks in advance for any help.

**Comment by crgeary** [comment]
What part are you stuck on? ... Installing the plugin? Triggering deployments? Generating a static website? or some other area?

This plugin does not create a static website for you. See: #45 or #31 .. Perhaps that will help answer your questions.
